//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:38:16 AM GMT 
//


package uk.gov.govtalk.cm.envelope;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.govtalk.cm.envelope package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.govtalk.cm.envelope
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IDAuthentication }
     * 
     */
    public IDAuthentication createIDAuthentication() {
        return new IDAuthentication();
    }

    /**
     * Create an instance of {@link GovTalkMessage }
     * 
     */
    public GovTalkMessage createGovTalkMessage() {
        return new GovTalkMessage();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails }
     * 
     */
    public GovTalkMessage.GovTalkDetails createGovTalkMessageGovTalkDetails() {
        return new GovTalkMessage.GovTalkDetails();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails.GovTalkErrors }
     * 
     */
    public GovTalkMessage.GovTalkDetails.GovTalkErrors createGovTalkMessageGovTalkDetailsGovTalkErrors() {
        return new GovTalkMessage.GovTalkDetails.GovTalkErrors();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails.ChannelRouting }
     * 
     */
    public GovTalkMessage.GovTalkDetails.ChannelRouting createGovTalkMessageGovTalkDetailsChannelRouting() {
        return new GovTalkMessage.GovTalkDetails.ChannelRouting();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails.Keys }
     * 
     */
    public GovTalkMessage.GovTalkDetails.Keys createGovTalkMessageGovTalkDetailsKeys() {
        return new GovTalkMessage.GovTalkDetails.Keys();
    }

    /**
     * Create an instance of {@link GovTalkMessage.Header }
     * 
     */
    public GovTalkMessage.Header createGovTalkMessageHeader() {
        return new GovTalkMessage.Header();
    }

    /**
     * Create an instance of {@link GovTalkMessage.Header.MessageDetails }
     * 
     */
    public GovTalkMessage.Header.MessageDetails createGovTalkMessageHeaderMessageDetails() {
        return new GovTalkMessage.Header.MessageDetails();
    }

    /**
     * Create an instance of {@link IDAuthentication.Authentication }
     * 
     */
    public IDAuthentication.Authentication createIDAuthenticationAuthentication() {
        return new IDAuthentication.Authentication();
    }

    /**
     * Create an instance of {@link GovTalkMessage.Body }
     * 
     */
    public GovTalkMessage.Body createGovTalkMessageBody() {
        return new GovTalkMessage.Body();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails.TargetDetails }
     * 
     */
    public GovTalkMessage.GovTalkDetails.TargetDetails createGovTalkMessageGovTalkDetailsTargetDetails() {
        return new GovTalkMessage.GovTalkDetails.TargetDetails();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails.GatewayValidation }
     * 
     */
    public GovTalkMessage.GovTalkDetails.GatewayValidation createGovTalkMessageGovTalkDetailsGatewayValidation() {
        return new GovTalkMessage.GovTalkDetails.GatewayValidation();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails.GatewayAdditions }
     * 
     */
    public GovTalkMessage.GovTalkDetails.GatewayAdditions createGovTalkMessageGovTalkDetailsGatewayAdditions() {
        return new GovTalkMessage.GovTalkDetails.GatewayAdditions();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails.GovTalkErrors.Error }
     * 
     */
    public GovTalkMessage.GovTalkDetails.GovTalkErrors.Error createGovTalkMessageGovTalkDetailsGovTalkErrorsError() {
        return new GovTalkMessage.GovTalkDetails.GovTalkErrors.Error();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails.ChannelRouting.Channel }
     * 
     */
    public GovTalkMessage.GovTalkDetails.ChannelRouting.Channel createGovTalkMessageGovTalkDetailsChannelRoutingChannel() {
        return new GovTalkMessage.GovTalkDetails.ChannelRouting.Channel();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails.ChannelRouting.ID }
     * 
     */
    public GovTalkMessage.GovTalkDetails.ChannelRouting.ID createGovTalkMessageGovTalkDetailsChannelRoutingID() {
        return new GovTalkMessage.GovTalkDetails.ChannelRouting.ID();
    }

    /**
     * Create an instance of {@link GovTalkMessage.GovTalkDetails.Keys.Key }
     * 
     */
    public GovTalkMessage.GovTalkDetails.Keys.Key createGovTalkMessageGovTalkDetailsKeysKey() {
        return new GovTalkMessage.GovTalkDetails.Keys.Key();
    }

    /**
     * Create an instance of {@link GovTalkMessage.Header.SenderDetails }
     * 
     */
    public GovTalkMessage.Header.SenderDetails createGovTalkMessageHeaderSenderDetails() {
        return new GovTalkMessage.Header.SenderDetails();
    }

    /**
     * Create an instance of {@link GovTalkMessage.Header.MessageDetails.ResponseEndPoint }
     * 
     */
    public GovTalkMessage.Header.MessageDetails.ResponseEndPoint createGovTalkMessageHeaderMessageDetailsResponseEndPoint() {
        return new GovTalkMessage.Header.MessageDetails.ResponseEndPoint();
    }

}
