//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AllotmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllotmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}ShareClass"/>
 *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}NumShares"/>
 *         &lt;element name="AmountPaidDuePerShare">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AmountUnpaidPerShare">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="6"/>
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ShareCurrency" type="{http://xmlgw.companieshouse.gov.uk}current_iso3currency"/>
 *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}ShareValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllotmentType", propOrder = {
    "shareClass",
    "numShares",
    "amountPaidDuePerShare",
    "amountUnpaidPerShare",
    "shareCurrency",
    "shareValue"
})
public class AllotmentType {

    @XmlElement(name = "ShareClass", required = true)
    protected String shareClass;
    @XmlElement(name = "NumShares", required = true)
    protected BigInteger numShares;
    @XmlElement(name = "AmountPaidDuePerShare", required = true)
    protected BigDecimal amountPaidDuePerShare;
    @XmlElement(name = "AmountUnpaidPerShare", required = true)
    protected BigDecimal amountUnpaidPerShare;
    @XmlElement(name = "ShareCurrency", required = true)
    @XmlSchemaType(name = "string")
    protected CurrentIso3Currency shareCurrency;
    @XmlElement(name = "ShareValue", required = true)
    protected BigDecimal shareValue;

    /**
     * Gets the value of the shareClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareClass() {
        return shareClass;
    }

    /**
     * Sets the value of the shareClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareClass(String value) {
        this.shareClass = value;
    }

    /**
     * Gets the value of the numShares property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumShares() {
        return numShares;
    }

    /**
     * Sets the value of the numShares property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumShares(BigInteger value) {
        this.numShares = value;
    }

    /**
     * Gets the value of the amountPaidDuePerShare property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountPaidDuePerShare() {
        return amountPaidDuePerShare;
    }

    /**
     * Sets the value of the amountPaidDuePerShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountPaidDuePerShare(BigDecimal value) {
        this.amountPaidDuePerShare = value;
    }

    /**
     * Gets the value of the amountUnpaidPerShare property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountUnpaidPerShare() {
        return amountUnpaidPerShare;
    }

    /**
     * Sets the value of the amountUnpaidPerShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountUnpaidPerShare(BigDecimal value) {
        this.amountUnpaidPerShare = value;
    }

    /**
     * Gets the value of the shareCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentIso3Currency }
     *     
     */
    public CurrentIso3Currency getShareCurrency() {
        return shareCurrency;
    }

    /**
     * Sets the value of the shareCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentIso3Currency }
     *     
     */
    public void setShareCurrency(CurrentIso3Currency value) {
        this.shareCurrency = value;
    }

    /**
     * Gets the value of the shareValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getShareValue() {
        return shareValue;
    }

    /**
     * Sets the value of the shareValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setShareValue(BigDecimal value) {
        this.shareValue = value;
    }

}
