//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="NonEEA">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://xmlgw.companieshouse.gov.uk}PlaceRegistered" minOccurs="0"/>
 *                   &lt;element ref="{http://xmlgw.companieshouse.gov.uk}RegistrationNumber" minOccurs="0"/>
 *                   &lt;element name="LawGoverned">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}nonEmptyNameAddressString">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="50"/>
 *                         &lt;whiteSpace value="collapse"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="LegalForm">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}nonEmptyOtherDataString">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="50"/>
 *                         &lt;whiteSpace value="collapse"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EEA">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://xmlgw.companieshouse.gov.uk}PlaceRegistered"/>
 *                   &lt;element ref="{http://xmlgw.companieshouse.gov.uk}RegistrationNumber"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nonEEA",
    "eea"
})
@XmlRootElement(name = "CompanyIdentification")
public class CompanyIdentification {

    @XmlElement(name = "NonEEA")
    protected CompanyIdentification.NonEEA nonEEA;
    @XmlElement(name = "EEA")
    protected CompanyIdentification.EEA eea;

    /**
     * Gets the value of the nonEEA property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyIdentification.NonEEA }
     *     
     */
    public CompanyIdentification.NonEEA getNonEEA() {
        return nonEEA;
    }

    /**
     * Sets the value of the nonEEA property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyIdentification.NonEEA }
     *     
     */
    public void setNonEEA(CompanyIdentification.NonEEA value) {
        this.nonEEA = value;
    }

    /**
     * Gets the value of the eea property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyIdentification.EEA }
     *     
     */
    public CompanyIdentification.EEA getEEA() {
        return eea;
    }

    /**
     * Sets the value of the eea property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyIdentification.EEA }
     *     
     */
    public void setEEA(CompanyIdentification.EEA value) {
        this.eea = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}PlaceRegistered"/>
     *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}RegistrationNumber"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "placeRegistered",
        "registrationNumber"
    })
    public static class EEA {

        @XmlElement(name = "PlaceRegistered", required = true)
        protected String placeRegistered;
        @XmlElement(name = "RegistrationNumber", required = true)
        protected String registrationNumber;

        /**
         * Gets the value of the placeRegistered property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlaceRegistered() {
            return placeRegistered;
        }

        /**
         * Sets the value of the placeRegistered property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlaceRegistered(String value) {
            this.placeRegistered = value;
        }

        /**
         * Gets the value of the registrationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegistrationNumber() {
            return registrationNumber;
        }

        /**
         * Sets the value of the registrationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegistrationNumber(String value) {
            this.registrationNumber = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}PlaceRegistered" minOccurs="0"/>
     *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}RegistrationNumber" minOccurs="0"/>
     *         &lt;element name="LawGoverned">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}nonEmptyNameAddressString">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="50"/>
     *               &lt;whiteSpace value="collapse"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LegalForm">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}nonEmptyOtherDataString">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="50"/>
     *               &lt;whiteSpace value="collapse"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "placeRegistered",
        "registrationNumber",
        "lawGoverned",
        "legalForm"
    })
    public static class NonEEA {

        @XmlElement(name = "PlaceRegistered")
        protected String placeRegistered;
        @XmlElement(name = "RegistrationNumber")
        protected String registrationNumber;
        @XmlElement(name = "LawGoverned", required = true)
        protected String lawGoverned;
        @XmlElement(name = "LegalForm", required = true)
        protected String legalForm;

        /**
         * Gets the value of the placeRegistered property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlaceRegistered() {
            return placeRegistered;
        }

        /**
         * Sets the value of the placeRegistered property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlaceRegistered(String value) {
            this.placeRegistered = value;
        }

        /**
         * Gets the value of the registrationNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegistrationNumber() {
            return registrationNumber;
        }

        /**
         * Sets the value of the registrationNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegistrationNumber(String value) {
            this.registrationNumber = value;
        }

        /**
         * Gets the value of the lawGoverned property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLawGoverned() {
            return lawGoverned;
        }

        /**
         * Sets the value of the lawGoverned property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLawGoverned(String value) {
            this.lawGoverned = value;
        }

        /**
         * Gets the value of the legalForm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLegalForm() {
            return legalForm;
        }

        /**
         * Sets the value of the legalForm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLegalForm(String value) {
            this.legalForm = value;
        }

    }

}
