//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A Company Director Appointment 
 * 
 * <p>Java class for DirectorAppointmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectorAppointmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Person">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://xmlgw.companieshouse.gov.uk}DirectorPersonType">
 *                 &lt;sequence>
 *                   &lt;element name="ResidentialAddress">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://xmlgw.companieshouse.gov.uk}ResidentialAddressType">
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Corporate" type="{http://xmlgw.companieshouse.gov.uk}CorporateOfficerAppointmentType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectorAppointmentType", propOrder = {
    "person",
    "corporate"
})
public class DirectorAppointmentType {

    @XmlElement(name = "Person")
    protected DirectorAppointmentType.Person person;
    @XmlElement(name = "Corporate")
    protected CorporateOfficerAppointmentType corporate;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link DirectorAppointmentType.Person }
     *     
     */
    public DirectorAppointmentType.Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectorAppointmentType.Person }
     *     
     */
    public void setPerson(DirectorAppointmentType.Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the corporate property.
     * 
     * @return
     *     possible object is
     *     {@link CorporateOfficerAppointmentType }
     *     
     */
    public CorporateOfficerAppointmentType getCorporate() {
        return corporate;
    }

    /**
     * Sets the value of the corporate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorporateOfficerAppointmentType }
     *     
     */
    public void setCorporate(CorporateOfficerAppointmentType value) {
        this.corporate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://xmlgw.companieshouse.gov.uk}DirectorPersonType">
     *       &lt;sequence>
     *         &lt;element name="ResidentialAddress">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://xmlgw.companieshouse.gov.uk}ResidentialAddressType">
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "residentialAddress"
    })
    public static class Person
        extends DirectorPersonType
    {

        @XmlElement(name = "ResidentialAddress", required = true)
        protected DirectorAppointmentType.Person.ResidentialAddress residentialAddress;

        /**
         * Gets the value of the residentialAddress property.
         * 
         * @return
         *     possible object is
         *     {@link DirectorAppointmentType.Person.ResidentialAddress }
         *     
         */
        public DirectorAppointmentType.Person.ResidentialAddress getResidentialAddress() {
            return residentialAddress;
        }

        /**
         * Sets the value of the residentialAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link DirectorAppointmentType.Person.ResidentialAddress }
         *     
         */
        public void setResidentialAddress(DirectorAppointmentType.Person.ResidentialAddress value) {
            this.residentialAddress = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://xmlgw.companieshouse.gov.uk}ResidentialAddressType">
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ResidentialAddress
            extends ResidentialAddressType
        {


        }

    }

}
