//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IssuedShareType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IssuedShareType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://xmlgw.companieshouse.gov.uk}ShareQuantityClassType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}AggregrateNominalValue"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IssuedShareType", propOrder = {
    "aggregrateNominalValue"
})
public class IssuedShareType
    extends ShareQuantityClassType
{

    @XmlElement(name = "AggregrateNominalValue", required = true)
    protected BigDecimal aggregrateNominalValue;

    /**
     * Gets the value of the aggregrateNominalValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAggregrateNominalValue() {
        return aggregrateNominalValue;
    }

    /**
     * Sets the value of the aggregrateNominalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAggregrateNominalValue(BigDecimal value) {
        this.aggregrateNominalValue = value;
    }

}
