//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.companieshouse.xmlgw package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocBeingScanned_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DocBeingScanned");
    private final static QName _RegAddress_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "RegAddress");
    private final static QName _NumMortPartSatisfied_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumMortPartSatisfied");
    private final static QName _AccountCategory_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AccountCategory");
    private final static QName _AppointmentStatus_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AppointmentStatus");
    private final static QName _DataSet_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DataSet");
    private final static QName _InstrumentDescription_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "InstrumentDescription");
    private final static QName _CreationDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CreationDate");
    private final static QName _SatisfiedChargesInd_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "SatisfiedChargesInd");
    private final static QName _CareofName_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CareofName");
    private final static QName _Street_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Street");
    private final static QName _NumResignedAppt_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumResignedAppt");
    private final static QName _PersonalAuthenitcationItem_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PersonalAuthenitcationItem");
    private final static QName _CompanyNumber_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CompanyNumber");
    private final static QName _PersonID_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PersonID");
    private final static QName _DetailsOnFicheInd_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DetailsOnFicheInd");
    private final static QName _NumAppInd_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumAppInd");
    private final static QName _Currency_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Currency");
    private final static QName _NumCurrentAppt_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumCurrentAppt");
    private final static QName _DOB_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DOB");
    private final static QName _NumShares_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumShares");
    private final static QName _CompanyStatus_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CompanyStatus");
    private final static QName _FormType_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "FormType");
    private final static QName _UserReference_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "UserReference");
    private final static QName _GiveMortTotals_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "GiveMortTotals");
    private final static QName _LastBulkShareDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "LastBulkShareDate");
    private final static QName _SICCode_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "SICCode");
    private final static QName _PostCode_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PostCode");
    private final static QName _Country_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Country");
    private final static QName _PersonalAuthentication_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PersonalAuthentication");
    private final static QName _ServiceAddressInd_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ServiceAddressInd");
    private final static QName _OfficerType_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "OfficerType");
    private final static QName _NumDissolvedAppt_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumDissolvedAppt");
    private final static QName _IncludeResignedInd_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "IncludeResignedInd");
    private final static QName _AppointmentType_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AppointmentType");
    private final static QName _ShareClass_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ShareClass");
    private final static QName _OfficerAppointment_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "OfficerAppointment");
    private final static QName _CONDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CONDate");
    private final static QName _ShareValue_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ShareValue");
    private final static QName _PersonalAuthenticationCode_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PersonalAuthenticationCode");
    private final static QName _RegistrationDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "RegistrationDate");
    private final static QName _ConsentToAct_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ConsentToAct");
    private final static QName _Description_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Description");
    private final static QName _Weeded_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Weeded");
    private final static QName _NumAppointments_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumAppointments");
    private final static QName _MadeUpDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "MadeUpDate");
    private final static QName _RegistrationNumber_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "RegistrationNumber");
    private final static QName _NumMortSatisfied_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumMortSatisfied");
    private final static QName _DissolutionDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DissolutionDate");
    private final static QName _AlterationToChgInd_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AlterationToChgInd");
    private final static QName _IncorporationAppointmentType_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "IncorporationAppointmentType");
    private final static QName _NextDueDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NextDueDate");
    private final static QName _EndDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "EndDate");
    private final static QName _CorporateName_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CorporateName");
    private final static QName _Nationality_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Nationality");
    private final static QName _Designation_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Designation");
    private final static QName _Thoroughfare_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Thoroughfare");
    private final static QName _Surname_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Surname");
    private final static QName _DocumentDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DocumentDate");
    private final static QName _ShortParticulars_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ShortParticulars");
    private final static QName _PropertyAcquiredDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PropertyAcquiredDate");
    private final static QName _CapitalDocInd_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CapitalDocInd");
    private final static QName _NominalCapital_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NominalCapital");
    private final static QName _ExistingChargeKey_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ExistingChargeKey");
    private final static QName _DocumentAvailable_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DocumentAvailable");
    private final static QName _HasUKEstablishment_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "HasUKEstablishment");
    private final static QName _NumGenPartners_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumGenPartners");
    private final static QName _CompanyIndexStatus_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CompanyIndexStatus");
    private final static QName _ChargeSatisfied_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ChargeSatisfied");
    private final static QName _SICText_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "SICText");
    private final static QName _NumMortCharges_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumMortCharges");
    private final static QName _AggregrateNominalValue_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AggregrateNominalValue");
    private final static QName _Occupation_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Occupation");
    private final static QName _ClosureDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ClosureDate");
    private final static QName _CorporateIndicator_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CorporateIndicator");
    private final static QName _DocumentCategory_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DocumentCategory");
    private final static QName _WeededDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "WeededDate");
    private final static QName _PersonsEntitled_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PersonsEntitled");
    private final static QName _CountryOfOrigin_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CountryOfOrigin");
    private final static QName _PostTown_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PostTown");
    private final static QName _SatisfiedDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "SatisfiedDate");
    private final static QName _AmountUnpaid_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AmountUnpaid");
    private final static QName _ChargeDescription_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ChargeDescription");
    private final static QName _PersonalAuthenticationData_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PersonalAuthenticationData");
    private final static QName _CoSearchItem_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CoSearchItem");
    private final static QName _CompanyAuthenticationCode_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CompanyAuthenticationCode");
    private final static QName _DocumentName_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DocumentName");
    private final static QName _SICCodes_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "SICCodes");
    private final static QName _DocumentDesc_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DocumentDesc");
    private final static QName _NumPages_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumPages");
    private final static QName _CompanyName_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CompanyName");
    private final static QName _ApptDatePrefix_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ApptDatePrefix");
    private final static QName _StartDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "StartDate");
    private final static QName _Postcode_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Postcode");
    private final static QName _Overdue_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Overdue");
    private final static QName _ContinuationKey_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ContinuationKey");
    private final static QName _AppointmentDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AppointmentDate");
    private final static QName _Media_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Media");
    private final static QName _NumDisqualOrders_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumDisqualOrders");
    private final static QName _ForeignAddress_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ForeignAddress");
    private final static QName _MortgageInd_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "MortgageInd");
    private final static QName _AddressLine_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AddressLine");
    private final static QName _LastMadeUpDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "LastMadeUpDate");
    private final static QName _AmountPaidUp_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AmountPaidUp");
    private final static QName _ResignationDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ResignationDate");
    private final static QName _OtherForenames_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "OtherForenames");
    private final static QName _CompanyDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CompanyDate");
    private final static QName _SearchRows_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "SearchRows");
    private final static QName _ImageKey_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ImageKey");
    private final static QName _AccountRefDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AccountRefDate");
    private final static QName _PreviousNames_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PreviousNames");
    private final static QName _PoBox_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PoBox");
    private final static QName _ChargeCode_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ChargeCode");
    private final static QName _HasAppointments_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "HasAppointments");
    private final static QName _County_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "County");
    private final static QName _Premise_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Premise");
    private final static QName _NumMortOutstanding_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumMortOutstanding");
    private final static QName _DocRequestKey_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DocRequestKey");
    private final static QName _LastFullMemDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "LastFullMemDate");
    private final static QName _InLiquidation_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "InLiquidation");
    private final static QName _ChargeNumber_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ChargeNumber");
    private final static QName _SecureAddressInd_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "SecureAddressInd");
    private final static QName _PlaceRegistered_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PlaceRegistered");
    private final static QName _RecordType_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "RecordType");
    private final static QName _Forename_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Forename");
    private final static QName _AcquisitionDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AcquisitionDate");
    private final static QName _ReceiverAptdInd_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "ReceiverAptdInd");
    private final static QName _NumLimPartners_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumLimPartners");
    private final static QName _SubmissionNumber_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "SubmissionNumber");
    private final static QName _TotalAggregateNominalValue_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "TotalAggregateNominalValue");
    private final static QName _PartialCompanyNumber_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PartialCompanyNumber");
    private final static QName _Title_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "Title");
    private final static QName _DocumentType_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "DocumentType");
    private final static QName _RegressionKey_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "RegressionKey");
    private final static QName _NumSharesIssued_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "NumSharesIssued");
    private final static QName _PersonEntChgName_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "PersonEntChgName");
    private final static QName _CountryOfResidence_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CountryOfResidence");
    private final static QName _SearchMatch_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "SearchMatch");
    private final static QName _IncorporationDate_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "IncorporationDate");
    private final static QName _CompanyCategory_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CompanyCategory");
    private final static QName _AdditionalPersonsEntitled_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "AdditionalPersonsEntitled");
    private final static QName _CountryStr_QNAME = new QName("http://xmlgw.companieshouse.gov.uk", "CountryStr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.companieshouse.xmlgw
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CompanyIdentification }
     * 
     */
    public CompanyIdentification createCompanyIdentification() {
        return new CompanyIdentification();
    }

    /**
     * Create an instance of {@link SecretaryAppointmentType }
     * 
     */
    public SecretaryAppointmentType createSecretaryAppointmentType() {
        return new SecretaryAppointmentType();
    }

    /**
     * Create an instance of {@link MemberAppointmentType }
     * 
     */
    public MemberAppointmentType createMemberAppointmentType() {
        return new MemberAppointmentType();
    }

    /**
     * Create an instance of {@link DirectorType }
     * 
     */
    public DirectorType createDirectorType() {
        return new DirectorType();
    }

    /**
     * Create an instance of {@link MemberType }
     * 
     */
    public MemberType createMemberType() {
        return new MemberType();
    }

    /**
     * Create an instance of {@link ShareHolderType }
     * 
     */
    public ShareHolderType createShareHolderType() {
        return new ShareHolderType();
    }

    /**
     * Create an instance of {@link OfficerAppointmentType }
     * 
     */
    public OfficerAppointmentType createOfficerAppointmentType() {
        return new OfficerAppointmentType();
    }

    /**
     * Create an instance of {@link OfficerAppointmentType.Appointee }
     * 
     */
    public OfficerAppointmentType.Appointee createOfficerAppointmentTypeAppointee() {
        return new OfficerAppointmentType.Appointee();
    }

    /**
     * Create an instance of {@link StatementOfCapitalType }
     * 
     */
    public StatementOfCapitalType createStatementOfCapitalType() {
        return new StatementOfCapitalType();
    }

    /**
     * Create an instance of {@link StatementOfCapitalType.Capital }
     * 
     */
    public StatementOfCapitalType.Capital createStatementOfCapitalTypeCapital() {
        return new StatementOfCapitalType.Capital();
    }

    /**
     * Create an instance of {@link DirectorAppointmentType }
     * 
     */
    public DirectorAppointmentType createDirectorAppointmentType() {
        return new DirectorAppointmentType();
    }

    /**
     * Create an instance of {@link DirectorAppointmentType.Person }
     * 
     */
    public DirectorAppointmentType.Person createDirectorAppointmentTypePerson() {
        return new DirectorAppointmentType.Person();
    }

    /**
     * Create an instance of {@link SecretaryReturnType }
     * 
     */
    public SecretaryReturnType createSecretaryReturnType() {
        return new SecretaryReturnType();
    }

    /**
     * Create an instance of {@link MemberReturnType }
     * 
     */
    public MemberReturnType createMemberReturnType() {
        return new MemberReturnType();
    }

    /**
     * Create an instance of {@link DirectorIncorporationAppointmentType }
     * 
     */
    public DirectorIncorporationAppointmentType createDirectorIncorporationAppointmentType() {
        return new DirectorIncorporationAppointmentType();
    }

    /**
     * Create an instance of {@link RegAddressType }
     * 
     */
    public RegAddressType createRegAddressType() {
        return new RegAddressType();
    }

    /**
     * Create an instance of {@link PersonalAttributeType }
     * 
     */
    public PersonalAttributeType createPersonalAttributeType() {
        return new PersonalAttributeType();
    }

    /**
     * Create an instance of {@link CompanyIdentification.NonEEA }
     * 
     */
    public CompanyIdentification.NonEEA createCompanyIdentificationNonEEA() {
        return new CompanyIdentification.NonEEA();
    }

    /**
     * Create an instance of {@link CompanyIdentification.EEA }
     * 
     */
    public CompanyIdentification.EEA createCompanyIdentificationEEA() {
        return new CompanyIdentification.EEA();
    }

    /**
     * Create an instance of {@link OfficerApptType }
     * 
     */
    public OfficerApptType createOfficerApptType() {
        return new OfficerApptType();
    }

    /**
     * Create an instance of {@link OfficerSearchItem }
     * 
     */
    public OfficerSearchItem createOfficerSearchItem() {
        return new OfficerSearchItem();
    }

    /**
     * Create an instance of {@link SICCodesType }
     * 
     */
    public SICCodesType createSICCodesType() {
        return new SICCodesType();
    }

    /**
     * Create an instance of {@link CoSearchCPLXType }
     * 
     */
    public CoSearchCPLXType createCoSearchCPLXType() {
        return new CoSearchCPLXType();
    }

    /**
     * Create an instance of {@link CoPreviousNamesType }
     * 
     */
    public CoPreviousNamesType createCoPreviousNamesType() {
        return new CoPreviousNamesType();
    }

    /**
     * Create an instance of {@link AnyAddressBaseType }
     * 
     */
    public AnyAddressBaseType createAnyAddressBaseType() {
        return new AnyAddressBaseType();
    }

    /**
     * Create an instance of {@link ShareQuantityClassType }
     * 
     */
    public ShareQuantityClassType createShareQuantityClassType() {
        return new ShareQuantityClassType();
    }

    /**
     * Create an instance of {@link AmalgamatedNameType }
     * 
     */
    public AmalgamatedNameType createAmalgamatedNameType() {
        return new AmalgamatedNameType();
    }

    /**
     * Create an instance of {@link UKAddressType }
     * 
     */
    public UKAddressType createUKAddressType() {
        return new UKAddressType();
    }

    /**
     * Create an instance of {@link PreviousNameType }
     * 
     */
    public PreviousNameType createPreviousNameType() {
        return new PreviousNameType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link ServiceAddressType }
     * 
     */
    public ServiceAddressType createServiceAddressType() {
        return new ServiceAddressType();
    }

    /**
     * Create an instance of {@link PersonChangeType }
     * 
     */
    public PersonChangeType createPersonChangeType() {
        return new PersonChangeType();
    }

    /**
     * Create an instance of {@link PersonBaseType }
     * 
     */
    public PersonBaseType createPersonBaseType() {
        return new PersonBaseType();
    }

    /**
     * Create an instance of {@link AddressTypeX }
     * 
     */
    public AddressTypeX createAddressTypeX() {
        return new AddressTypeX();
    }

    /**
     * Create an instance of {@link CompanyIdentifierType }
     * 
     */
    public CompanyIdentifierType createCompanyIdentifierType() {
        return new CompanyIdentifierType();
    }

    /**
     * Create an instance of {@link FooterDetails }
     * 
     */
    public FooterDetails createFooterDetails() {
        return new FooterDetails();
    }

    /**
     * Create an instance of {@link PersonAddrType }
     * 
     */
    public PersonAddrType createPersonAddrType() {
        return new PersonAddrType();
    }

    /**
     * Create an instance of {@link SecretaryType }
     * 
     */
    public SecretaryType createSecretaryType() {
        return new SecretaryType();
    }

    /**
     * Create an instance of {@link ShareholderNameType }
     * 
     */
    public ShareholderNameType createShareholderNameType() {
        return new ShareholderNameType();
    }

    /**
     * Create an instance of {@link DirectorReturnType }
     * 
     */
    public DirectorReturnType createDirectorReturnType() {
        return new DirectorReturnType();
    }

    /**
     * Create an instance of {@link CorporateOfficerType }
     * 
     */
    public CorporateOfficerType createCorporateOfficerType() {
        return new CorporateOfficerType();
    }

    /**
     * Create an instance of {@link DatePeriod }
     * 
     */
    public DatePeriod createDatePeriod() {
        return new DatePeriod();
    }

    /**
     * Create an instance of {@link CorporateOfficerAppointmentType }
     * 
     */
    public CorporateOfficerAppointmentType createCorporateOfficerAppointmentType() {
        return new CorporateOfficerAppointmentType();
    }

    /**
     * Create an instance of {@link CompanyAddressType }
     * 
     */
    public CompanyAddressType createCompanyAddressType() {
        return new CompanyAddressType();
    }

    /**
     * Create an instance of {@link DirectorPersonType }
     * 
     */
    public DirectorPersonType createDirectorPersonType() {
        return new DirectorPersonType();
    }

    /**
     * Create an instance of {@link AddressBaseType }
     * 
     */
    public AddressBaseType createAddressBaseType() {
        return new AddressBaseType();
    }

    /**
     * Create an instance of {@link PersCorpAuthType }
     * 
     */
    public PersCorpAuthType createPersCorpAuthType() {
        return new PersCorpAuthType();
    }

    /**
     * Create an instance of {@link SubsidiaryAndAssociatedUndertakingsType }
     * 
     */
    public SubsidiaryAndAssociatedUndertakingsType createSubsidiaryAndAssociatedUndertakingsType() {
        return new SubsidiaryAndAssociatedUndertakingsType();
    }

    /**
     * Create an instance of {@link CapitalType }
     * 
     */
    public CapitalType createCapitalType() {
        return new CapitalType();
    }

    /**
     * Create an instance of {@link PersonNameType }
     * 
     */
    public PersonNameType createPersonNameType() {
        return new PersonNameType();
    }

    /**
     * Create an instance of {@link AllotmentType }
     * 
     */
    public AllotmentType createAllotmentType() {
        return new AllotmentType();
    }

    /**
     * Create an instance of {@link DirectorAddressType }
     * 
     */
    public DirectorAddressType createDirectorAddressType() {
        return new DirectorAddressType();
    }

    /**
     * Create an instance of {@link ShareholderAddressType }
     * 
     */
    public ShareholderAddressType createShareholderAddressType() {
        return new ShareholderAddressType();
    }

    /**
     * Create an instance of {@link TotalShareCapitalType }
     * 
     */
    public TotalShareCapitalType createTotalShareCapitalType() {
        return new TotalShareCapitalType();
    }

    /**
     * Create an instance of {@link ResidentialAddressType }
     * 
     */
    public ResidentialAddressType createResidentialAddressType() {
        return new ResidentialAddressType();
    }

    /**
     * Create an instance of {@link ShareQuantityValueType }
     * 
     */
    public ShareQuantityValueType createShareQuantityValueType() {
        return new ShareQuantityValueType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link IssuedShareType }
     * 
     */
    public IssuedShareType createIssuedShareType() {
        return new IssuedShareType();
    }

    /**
     * Create an instance of {@link SecretaryAppointmentType.Person }
     * 
     */
    public SecretaryAppointmentType.Person createSecretaryAppointmentTypePerson() {
        return new SecretaryAppointmentType.Person();
    }

    /**
     * Create an instance of {@link MemberAppointmentType.Person }
     * 
     */
    public MemberAppointmentType.Person createMemberAppointmentTypePerson() {
        return new MemberAppointmentType.Person();
    }

    /**
     * Create an instance of {@link DirectorType.Person }
     * 
     */
    public DirectorType.Person createDirectorTypePerson() {
        return new DirectorType.Person();
    }

    /**
     * Create an instance of {@link MemberType.Person }
     * 
     */
    public MemberType.Person createMemberTypePerson() {
        return new MemberType.Person();
    }

    /**
     * Create an instance of {@link ShareHolderType.Person }
     * 
     */
    public ShareHolderType.Person createShareHolderTypePerson() {
        return new ShareHolderType.Person();
    }

    /**
     * Create an instance of {@link OfficerAppointmentType.Appointee.Individual }
     * 
     */
    public OfficerAppointmentType.Appointee.Individual createOfficerAppointmentTypeAppointeeIndividual() {
        return new OfficerAppointmentType.Appointee.Individual();
    }

    /**
     * Create an instance of {@link StatementOfCapitalType.Capital.Shares }
     * 
     */
    public StatementOfCapitalType.Capital.Shares createStatementOfCapitalTypeCapitalShares() {
        return new StatementOfCapitalType.Capital.Shares();
    }

    /**
     * Create an instance of {@link DirectorAppointmentType.Person.ResidentialAddress }
     * 
     */
    public DirectorAppointmentType.Person.ResidentialAddress createDirectorAppointmentTypePersonResidentialAddress() {
        return new DirectorAppointmentType.Person.ResidentialAddress();
    }

    /**
     * Create an instance of {@link SecretaryReturnType.Person }
     * 
     */
    public SecretaryReturnType.Person createSecretaryReturnTypePerson() {
        return new SecretaryReturnType.Person();
    }

    /**
     * Create an instance of {@link MemberReturnType.Person }
     * 
     */
    public MemberReturnType.Person createMemberReturnTypePerson() {
        return new MemberReturnType.Person();
    }

    /**
     * Create an instance of {@link DirectorIncorporationAppointmentType.Address }
     * 
     */
    public DirectorIncorporationAppointmentType.Address createDirectorIncorporationAppointmentTypeAddress() {
        return new DirectorIncorporationAppointmentType.Address();
    }

    /**
     * Create an instance of {@link DirectorIncorporationAppointmentType.Person }
     * 
     */
    public DirectorIncorporationAppointmentType.Person createDirectorIncorporationAppointmentTypePerson() {
        return new DirectorIncorporationAppointmentType.Person();
    }

    /**
     * Create an instance of {@link DirectorIncorporationAppointmentType.Corporate }
     * 
     */
    public DirectorIncorporationAppointmentType.Corporate createDirectorIncorporationAppointmentTypeCorporate() {
        return new DirectorIncorporationAppointmentType.Corporate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DocBeingScanned")
    public JAXBElement<Boolean> createDocBeingScanned(Boolean value) {
        return new JAXBElement<Boolean>(_DocBeingScanned_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "RegAddress")
    public JAXBElement<RegAddressType> createRegAddress(RegAddressType value) {
        return new JAXBElement<RegAddressType>(_RegAddress_QNAME, RegAddressType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumMortPartSatisfied")
    public JAXBElement<BigInteger> createNumMortPartSatisfied(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumMortPartSatisfied_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AccountCategory")
    public JAXBElement<String> createAccountCategory(String value) {
        return new JAXBElement<String>(_AccountCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AppointmentStatus")
    public JAXBElement<String> createAppointmentStatus(String value) {
        return new JAXBElement<String>(_AppointmentStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DataSet")
    public JAXBElement<String> createDataSet(String value) {
        return new JAXBElement<String>(_DataSet_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "InstrumentDescription")
    public JAXBElement<String> createInstrumentDescription(String value) {
        return new JAXBElement<String>(_InstrumentDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CreationDate")
    public JAXBElement<XMLGregorianCalendar> createCreationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "SatisfiedChargesInd")
    public JAXBElement<Boolean> createSatisfiedChargesInd(Boolean value) {
        return new JAXBElement<Boolean>(_SatisfiedChargesInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CareofName")
    public JAXBElement<String> createCareofName(String value) {
        return new JAXBElement<String>(_CareofName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Street")
    public JAXBElement<String> createStreet(String value) {
        return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumResignedAppt")
    public JAXBElement<BigInteger> createNumResignedAppt(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumResignedAppt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PersonalAuthenitcationItem")
    public JAXBElement<String> createPersonalAuthenitcationItem(String value) {
        return new JAXBElement<String>(_PersonalAuthenitcationItem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CompanyNumber")
    public JAXBElement<BigInteger> createCompanyNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_CompanyNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PersonID")
    public JAXBElement<String> createPersonID(String value) {
        return new JAXBElement<String>(_PersonID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DetailsOnFicheInd")
    public JAXBElement<Boolean> createDetailsOnFicheInd(Boolean value) {
        return new JAXBElement<Boolean>(_DetailsOnFicheInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumAppInd")
    public JAXBElement<String> createNumAppInd(String value) {
        return new JAXBElement<String>(_NumAppInd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Currency")
    public JAXBElement<String> createCurrency(String value) {
        return new JAXBElement<String>(_Currency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumCurrentAppt")
    public JAXBElement<BigInteger> createNumCurrentAppt(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumCurrentAppt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DOB")
    public JAXBElement<XMLGregorianCalendar> createDOB(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DOB_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumShares")
    public JAXBElement<BigInteger> createNumShares(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumShares_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CompanyStatus")
    public JAXBElement<String> createCompanyStatus(String value) {
        return new JAXBElement<String>(_CompanyStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "FormType")
    public JAXBElement<String> createFormType(String value) {
        return new JAXBElement<String>(_FormType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "UserReference")
    public JAXBElement<String> createUserReference(String value) {
        return new JAXBElement<String>(_UserReference_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "GiveMortTotals")
    public JAXBElement<Boolean> createGiveMortTotals(Boolean value) {
        return new JAXBElement<Boolean>(_GiveMortTotals_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "LastBulkShareDate")
    public JAXBElement<XMLGregorianCalendar> createLastBulkShareDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastBulkShareDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "SICCode")
    public JAXBElement<String> createSICCode(String value) {
        return new JAXBElement<String>(_SICCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PostCode")
    public JAXBElement<String> createPostCode(String value) {
        return new JAXBElement<String>(_PostCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonalAttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PersonalAuthentication")
    public JAXBElement<PersonalAttributeType> createPersonalAuthentication(PersonalAttributeType value) {
        return new JAXBElement<PersonalAttributeType>(_PersonalAuthentication_QNAME, PersonalAttributeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ServiceAddressInd")
    public JAXBElement<Boolean> createServiceAddressInd(Boolean value) {
        return new JAXBElement<Boolean>(_ServiceAddressInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "OfficerType")
    public JAXBElement<String> createOfficerType(String value) {
        return new JAXBElement<String>(_OfficerType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumDissolvedAppt")
    public JAXBElement<BigInteger> createNumDissolvedAppt(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumDissolvedAppt_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "IncludeResignedInd")
    public JAXBElement<Boolean> createIncludeResignedInd(Boolean value) {
        return new JAXBElement<Boolean>(_IncludeResignedInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AppointmentType")
    public JAXBElement<String> createAppointmentType(String value) {
        return new JAXBElement<String>(_AppointmentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ShareClass")
    public JAXBElement<String> createShareClass(String value) {
        return new JAXBElement<String>(_ShareClass_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfficerApptType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "OfficerAppointment")
    public JAXBElement<OfficerApptType> createOfficerAppointment(OfficerApptType value) {
        return new JAXBElement<OfficerApptType>(_OfficerAppointment_QNAME, OfficerApptType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CONDate")
    public JAXBElement<XMLGregorianCalendar> createCONDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CONDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ShareValue")
    public JAXBElement<BigDecimal> createShareValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_ShareValue_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PersonalAuthenticationCode")
    public JAXBElement<String> createPersonalAuthenticationCode(String value) {
        return new JAXBElement<String>(_PersonalAuthenticationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "RegistrationDate")
    public JAXBElement<XMLGregorianCalendar> createRegistrationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RegistrationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ConsentToAct")
    public JAXBElement<Boolean> createConsentToAct(Boolean value) {
        return new JAXBElement<Boolean>(_ConsentToAct_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Weeded")
    public JAXBElement<Boolean> createWeeded(Boolean value) {
        return new JAXBElement<Boolean>(_Weeded_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumAppointments")
    public JAXBElement<BigInteger> createNumAppointments(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumAppointments_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "MadeUpDate")
    public JAXBElement<XMLGregorianCalendar> createMadeUpDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_MadeUpDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "RegistrationNumber")
    public JAXBElement<String> createRegistrationNumber(String value) {
        return new JAXBElement<String>(_RegistrationNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumMortSatisfied")
    public JAXBElement<BigInteger> createNumMortSatisfied(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumMortSatisfied_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DissolutionDate")
    public JAXBElement<XMLGregorianCalendar> createDissolutionDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DissolutionDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AlterationToChgInd")
    public JAXBElement<Boolean> createAlterationToChgInd(Boolean value) {
        return new JAXBElement<Boolean>(_AlterationToChgInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "IncorporationAppointmentType")
    public JAXBElement<String> createIncorporationAppointmentType(String value) {
        return new JAXBElement<String>(_IncorporationAppointmentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NextDueDate")
    public JAXBElement<XMLGregorianCalendar> createNextDueDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_NextDueDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "EndDate")
    public JAXBElement<XMLGregorianCalendar> createEndDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_EndDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CorporateName")
    public JAXBElement<String> createCorporateName(String value) {
        return new JAXBElement<String>(_CorporateName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Nationality")
    public JAXBElement<String> createNationality(String value) {
        return new JAXBElement<String>(_Nationality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Designation")
    public JAXBElement<String> createDesignation(String value) {
        return new JAXBElement<String>(_Designation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Thoroughfare")
    public JAXBElement<String> createThoroughfare(String value) {
        return new JAXBElement<String>(_Thoroughfare_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Surname")
    public JAXBElement<String> createSurname(String value) {
        return new JAXBElement<String>(_Surname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DocumentDate")
    public JAXBElement<XMLGregorianCalendar> createDocumentDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DocumentDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ShortParticulars")
    public JAXBElement<String> createShortParticulars(String value) {
        return new JAXBElement<String>(_ShortParticulars_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PropertyAcquiredDate")
    public JAXBElement<XMLGregorianCalendar> createPropertyAcquiredDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PropertyAcquiredDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CapitalDocInd")
    public JAXBElement<Boolean> createCapitalDocInd(Boolean value) {
        return new JAXBElement<Boolean>(_CapitalDocInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NominalCapital")
    public JAXBElement<BigDecimal> createNominalCapital(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NominalCapital_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ExistingChargeKey")
    public JAXBElement<Object> createExistingChargeKey(Object value) {
        return new JAXBElement<Object>(_ExistingChargeKey_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DocumentAvailable")
    public JAXBElement<Boolean> createDocumentAvailable(Boolean value) {
        return new JAXBElement<Boolean>(_DocumentAvailable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "HasUKEstablishment")
    public JAXBElement<Boolean> createHasUKEstablishment(Boolean value) {
        return new JAXBElement<Boolean>(_HasUKEstablishment_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumGenPartners")
    public JAXBElement<BigInteger> createNumGenPartners(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumGenPartners_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CompanyIndexStatus")
    public JAXBElement<String> createCompanyIndexStatus(String value) {
        return new JAXBElement<String>(_CompanyIndexStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ChargeSatisfied")
    public JAXBElement<String> createChargeSatisfied(String value) {
        return new JAXBElement<String>(_ChargeSatisfied_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "SICText")
    public JAXBElement<String> createSICText(String value) {
        return new JAXBElement<String>(_SICText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumMortCharges")
    public JAXBElement<BigInteger> createNumMortCharges(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumMortCharges_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AggregrateNominalValue")
    public JAXBElement<BigDecimal> createAggregrateNominalValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_AggregrateNominalValue_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Occupation")
    public JAXBElement<String> createOccupation(String value) {
        return new JAXBElement<String>(_Occupation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ClosureDate")
    public JAXBElement<XMLGregorianCalendar> createClosureDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ClosureDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CorporateIndicator")
    public JAXBElement<Boolean> createCorporateIndicator(Boolean value) {
        return new JAXBElement<Boolean>(_CorporateIndicator_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DocumentCategory")
    public JAXBElement<Integer> createDocumentCategory(Integer value) {
        return new JAXBElement<Integer>(_DocumentCategory_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "WeededDate")
    public JAXBElement<XMLGregorianCalendar> createWeededDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_WeededDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PersonsEntitled")
    public JAXBElement<String> createPersonsEntitled(String value) {
        return new JAXBElement<String>(_PersonsEntitled_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CountryOfOrigin")
    public JAXBElement<String> createCountryOfOrigin(String value) {
        return new JAXBElement<String>(_CountryOfOrigin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PostTown")
    public JAXBElement<String> createPostTown(String value) {
        return new JAXBElement<String>(_PostTown_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "SatisfiedDate")
    public JAXBElement<XMLGregorianCalendar> createSatisfiedDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_SatisfiedDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AmountUnpaid")
    public JAXBElement<BigDecimal> createAmountUnpaid(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_AmountUnpaid_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ChargeDescription")
    public JAXBElement<String> createChargeDescription(String value) {
        return new JAXBElement<String>(_ChargeDescription_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PersonalAuthenticationData")
    public JAXBElement<String> createPersonalAuthenticationData(String value) {
        return new JAXBElement<String>(_PersonalAuthenticationData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoSearchCPLXType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CoSearchItem")
    public JAXBElement<CoSearchCPLXType> createCoSearchItem(CoSearchCPLXType value) {
        return new JAXBElement<CoSearchCPLXType>(_CoSearchItem_QNAME, CoSearchCPLXType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CompanyAuthenticationCode")
    public JAXBElement<String> createCompanyAuthenticationCode(String value) {
        return new JAXBElement<String>(_CompanyAuthenticationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DocumentName")
    public JAXBElement<String> createDocumentName(String value) {
        return new JAXBElement<String>(_DocumentName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SICCodesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "SICCodes")
    public JAXBElement<SICCodesType> createSICCodes(SICCodesType value) {
        return new JAXBElement<SICCodesType>(_SICCodes_QNAME, SICCodesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DocumentDesc")
    public JAXBElement<String> createDocumentDesc(String value) {
        return new JAXBElement<String>(_DocumentDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumPages")
    public JAXBElement<BigInteger> createNumPages(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumPages_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CompanyName")
    public JAXBElement<String> createCompanyName(String value) {
        return new JAXBElement<String>(_CompanyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ApptDatePrefix")
    public JAXBElement<String> createApptDatePrefix(String value) {
        return new JAXBElement<String>(_ApptDatePrefix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "StartDate")
    public JAXBElement<XMLGregorianCalendar> createStartDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_StartDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Postcode")
    public JAXBElement<String> createPostcode(String value) {
        return new JAXBElement<String>(_Postcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Overdue")
    public JAXBElement<String> createOverdue(String value) {
        return new JAXBElement<String>(_Overdue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ContinuationKey")
    public JAXBElement<String> createContinuationKey(String value) {
        return new JAXBElement<String>(_ContinuationKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AppointmentDate")
    public JAXBElement<XMLGregorianCalendar> createAppointmentDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AppointmentDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Media")
    public JAXBElement<String> createMedia(String value) {
        return new JAXBElement<String>(_Media_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumDisqualOrders")
    public JAXBElement<BigInteger> createNumDisqualOrders(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumDisqualOrders_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ForeignAddress")
    public JAXBElement<Boolean> createForeignAddress(Boolean value) {
        return new JAXBElement<Boolean>(_ForeignAddress_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "MortgageInd")
    public JAXBElement<String> createMortgageInd(String value) {
        return new JAXBElement<String>(_MortgageInd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AddressLine")
    public JAXBElement<String> createAddressLine(String value) {
        return new JAXBElement<String>(_AddressLine_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "LastMadeUpDate")
    public JAXBElement<XMLGregorianCalendar> createLastMadeUpDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastMadeUpDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AmountPaidUp")
    public JAXBElement<BigDecimal> createAmountPaidUp(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_AmountPaidUp_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ResignationDate")
    public JAXBElement<XMLGregorianCalendar> createResignationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ResignationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "OtherForenames")
    public JAXBElement<String> createOtherForenames(String value) {
        return new JAXBElement<String>(_OtherForenames_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CompanyDate")
    public JAXBElement<XMLGregorianCalendar> createCompanyDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CompanyDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "SearchRows")
    public JAXBElement<BigInteger> createSearchRows(BigInteger value) {
        return new JAXBElement<BigInteger>(_SearchRows_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ImageKey")
    public JAXBElement<String> createImageKey(String value) {
        return new JAXBElement<String>(_ImageKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AccountRefDate")
    public JAXBElement<XMLGregorianCalendar> createAccountRefDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AccountRefDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoPreviousNamesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PreviousNames")
    public JAXBElement<CoPreviousNamesType> createPreviousNames(CoPreviousNamesType value) {
        return new JAXBElement<CoPreviousNamesType>(_PreviousNames_QNAME, CoPreviousNamesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PoBox")
    public JAXBElement<String> createPoBox(String value) {
        return new JAXBElement<String>(_PoBox_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ChargeCode")
    public JAXBElement<String> createChargeCode(String value) {
        return new JAXBElement<String>(_ChargeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "HasAppointments")
    public JAXBElement<Boolean> createHasAppointments(Boolean value) {
        return new JAXBElement<Boolean>(_HasAppointments_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "County")
    public JAXBElement<String> createCounty(String value) {
        return new JAXBElement<String>(_County_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Premise")
    public JAXBElement<String> createPremise(String value) {
        return new JAXBElement<String>(_Premise_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumMortOutstanding")
    public JAXBElement<BigInteger> createNumMortOutstanding(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumMortOutstanding_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DocRequestKey")
    public JAXBElement<String> createDocRequestKey(String value) {
        return new JAXBElement<String>(_DocRequestKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "LastFullMemDate")
    public JAXBElement<XMLGregorianCalendar> createLastFullMemDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_LastFullMemDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "InLiquidation")
    public JAXBElement<Boolean> createInLiquidation(Boolean value) {
        return new JAXBElement<Boolean>(_InLiquidation_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ChargeNumber")
    public JAXBElement<BigInteger> createChargeNumber(BigInteger value) {
        return new JAXBElement<BigInteger>(_ChargeNumber_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "SecureAddressInd")
    public JAXBElement<Boolean> createSecureAddressInd(Boolean value) {
        return new JAXBElement<Boolean>(_SecureAddressInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PlaceRegistered")
    public JAXBElement<String> createPlaceRegistered(String value) {
        return new JAXBElement<String>(_PlaceRegistered_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "RecordType")
    public JAXBElement<String> createRecordType(String value) {
        return new JAXBElement<String>(_RecordType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Forename")
    public JAXBElement<String> createForename(String value) {
        return new JAXBElement<String>(_Forename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AcquisitionDate")
    public JAXBElement<XMLGregorianCalendar> createAcquisitionDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_AcquisitionDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "ReceiverAptdInd")
    public JAXBElement<Boolean> createReceiverAptdInd(Boolean value) {
        return new JAXBElement<Boolean>(_ReceiverAptdInd_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumLimPartners")
    public JAXBElement<BigInteger> createNumLimPartners(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumLimPartners_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "SubmissionNumber")
    public JAXBElement<String> createSubmissionNumber(String value) {
        return new JAXBElement<String>(_SubmissionNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "TotalAggregateNominalValue")
    public JAXBElement<BigDecimal> createTotalAggregateNominalValue(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TotalAggregateNominalValue_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PartialCompanyNumber")
    public JAXBElement<String> createPartialCompanyNumber(String value) {
        return new JAXBElement<String>(_PartialCompanyNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "Title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "DocumentType")
    public JAXBElement<String> createDocumentType(String value) {
        return new JAXBElement<String>(_DocumentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "RegressionKey")
    public JAXBElement<String> createRegressionKey(String value) {
        return new JAXBElement<String>(_RegressionKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "NumSharesIssued")
    public JAXBElement<BigInteger> createNumSharesIssued(BigInteger value) {
        return new JAXBElement<BigInteger>(_NumSharesIssued_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "PersonEntChgName")
    public JAXBElement<String> createPersonEntChgName(String value) {
        return new JAXBElement<String>(_PersonEntChgName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CountryOfResidence")
    public JAXBElement<String> createCountryOfResidence(String value) {
        return new JAXBElement<String>(_CountryOfResidence_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "SearchMatch")
    public JAXBElement<String> createSearchMatch(String value) {
        return new JAXBElement<String>(_SearchMatch_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "IncorporationDate")
    public JAXBElement<XMLGregorianCalendar> createIncorporationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IncorporationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CompanyCategory")
    public JAXBElement<String> createCompanyCategory(String value) {
        return new JAXBElement<String>(_CompanyCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "AdditionalPersonsEntitled")
    public JAXBElement<String> createAdditionalPersonsEntitled(String value) {
        return new JAXBElement<String>(_AdditionalPersonsEntitled_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlgw.companieshouse.gov.uk", name = "CountryStr")
    public JAXBElement<String> createCountryStr(String value) {
        return new JAXBElement<String>(_CountryStr_QNAME, String.class, null, value);
    }

}
