//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfficerAppointmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfficerAppointmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Appointee">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Individual">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Person" type="{http://xmlgw.companieshouse.gov.uk}PersonType"/>
 *                             &lt;element name="PreviousName" type="{http://xmlgw.companieshouse.gov.uk}NameType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://xmlgw.companieshouse.gov.uk}CorporateName"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Address" type="{http://xmlgw.companieshouse.gov.uk}DirectorAddressType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfficerAppointmentType", propOrder = {
    "appointee",
    "address"
})
public class OfficerAppointmentType {

    @XmlElement(name = "Appointee", required = true)
    protected OfficerAppointmentType.Appointee appointee;
    @XmlElement(name = "Address", required = true)
    protected DirectorAddressType address;

    /**
     * Gets the value of the appointee property.
     * 
     * @return
     *     possible object is
     *     {@link OfficerAppointmentType.Appointee }
     *     
     */
    public OfficerAppointmentType.Appointee getAppointee() {
        return appointee;
    }

    /**
     * Sets the value of the appointee property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfficerAppointmentType.Appointee }
     *     
     */
    public void setAppointee(OfficerAppointmentType.Appointee value) {
        this.appointee = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link DirectorAddressType }
     *     
     */
    public DirectorAddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectorAddressType }
     *     
     */
    public void setAddress(DirectorAddressType value) {
        this.address = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Individual">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Person" type="{http://xmlgw.companieshouse.gov.uk}PersonType"/>
     *                   &lt;element name="PreviousName" type="{http://xmlgw.companieshouse.gov.uk}NameType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}CorporateName"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "individual",
        "corporateName"
    })
    public static class Appointee {

        @XmlElement(name = "Individual")
        protected OfficerAppointmentType.Appointee.Individual individual;
        @XmlElement(name = "CorporateName")
        protected String corporateName;

        /**
         * Gets the value of the individual property.
         * 
         * @return
         *     possible object is
         *     {@link OfficerAppointmentType.Appointee.Individual }
         *     
         */
        public OfficerAppointmentType.Appointee.Individual getIndividual() {
            return individual;
        }

        /**
         * Sets the value of the individual property.
         * 
         * @param value
         *     allowed object is
         *     {@link OfficerAppointmentType.Appointee.Individual }
         *     
         */
        public void setIndividual(OfficerAppointmentType.Appointee.Individual value) {
            this.individual = value;
        }

        /**
         * Gets the value of the corporateName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCorporateName() {
            return corporateName;
        }

        /**
         * Sets the value of the corporateName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCorporateName(String value) {
            this.corporateName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Person" type="{http://xmlgw.companieshouse.gov.uk}PersonType"/>
         *         &lt;element name="PreviousName" type="{http://xmlgw.companieshouse.gov.uk}NameType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "person",
            "previousName"
        })
        public static class Individual {

            @XmlElement(name = "Person", required = true)
            protected PersonType person;
            @XmlElement(name = "PreviousName")
            protected NameType previousName;

            /**
             * Gets the value of the person property.
             * 
             * @return
             *     possible object is
             *     {@link PersonType }
             *     
             */
            public PersonType getPerson() {
                return person;
            }

            /**
             * Sets the value of the person property.
             * 
             * @param value
             *     allowed object is
             *     {@link PersonType }
             *     
             */
            public void setPerson(PersonType value) {
                this.person = value;
            }

            /**
             * Gets the value of the previousName property.
             * 
             * @return
             *     possible object is
             *     {@link NameType }
             *     
             */
            public NameType getPreviousName() {
                return previousName;
            }

            /**
             * Sets the value of the previousName property.
             * 
             * @param value
             *     allowed object is
             *     {@link NameType }
             *     
             */
            public void setPreviousName(NameType value) {
                this.previousName = value;
            }

        }

    }

}
