//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Appointment of an Officer
 * 
 * <p>Java class for OfficerApptType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfficerApptType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}AppointmentDate"/>
 *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}ConsentToAct"/>
 *         &lt;choice>
 *           &lt;element name="Director" type="{http://xmlgw.companieshouse.gov.uk}DirectorAppointmentType"/>
 *           &lt;element name="Secretary" type="{http://xmlgw.companieshouse.gov.uk}SecretaryAppointmentType"/>
 *           &lt;element name="Member" type="{http://xmlgw.companieshouse.gov.uk}MemberAppointmentType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfficerApptType", propOrder = {
    "appointmentDate",
    "consentToAct",
    "director",
    "secretary",
    "member"
})
public class OfficerApptType {

    @XmlElement(name = "AppointmentDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar appointmentDate;
    @XmlElement(name = "ConsentToAct")
    protected boolean consentToAct;
    @XmlElement(name = "Director")
    protected DirectorAppointmentType director;
    @XmlElement(name = "Secretary")
    protected SecretaryAppointmentType secretary;
    @XmlElement(name = "Member")
    protected MemberAppointmentType member;

    /**
     * Gets the value of the appointmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAppointmentDate() {
        return appointmentDate;
    }

    /**
     * Sets the value of the appointmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAppointmentDate(XMLGregorianCalendar value) {
        this.appointmentDate = value;
    }

    /**
     * Gets the value of the consentToAct property.
     * 
     */
    public boolean isConsentToAct() {
        return consentToAct;
    }

    /**
     * Sets the value of the consentToAct property.
     * 
     */
    public void setConsentToAct(boolean value) {
        this.consentToAct = value;
    }

    /**
     * Gets the value of the director property.
     * 
     * @return
     *     possible object is
     *     {@link DirectorAppointmentType }
     *     
     */
    public DirectorAppointmentType getDirector() {
        return director;
    }

    /**
     * Sets the value of the director property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectorAppointmentType }
     *     
     */
    public void setDirector(DirectorAppointmentType value) {
        this.director = value;
    }

    /**
     * Gets the value of the secretary property.
     * 
     * @return
     *     possible object is
     *     {@link SecretaryAppointmentType }
     *     
     */
    public SecretaryAppointmentType getSecretary() {
        return secretary;
    }

    /**
     * Sets the value of the secretary property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecretaryAppointmentType }
     *     
     */
    public void setSecretary(SecretaryAppointmentType value) {
        this.secretary = value;
    }

    /**
     * Gets the value of the member property.
     * 
     * @return
     *     possible object is
     *     {@link MemberAppointmentType }
     *     
     */
    public MemberAppointmentType getMember() {
        return member;
    }

    /**
     * Sets the value of the member property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberAppointmentType }
     *     
     */
    public void setMember(MemberAppointmentType value) {
        this.member = value;
    }

}
