//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonalAttributeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonalAttributeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PersonalAttribute">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="BIRTOWN"/>
 *               &lt;enumeration value="TEL"/>
 *               &lt;enumeration value="NATINS"/>
 *               &lt;enumeration value="PASSNO"/>
 *               &lt;enumeration value="MUM"/>
 *               &lt;enumeration value="EYE"/>
 *               &lt;enumeration value="DAD"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PersonalData">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}nonEmptyOtherDataString">
 *               &lt;minLength value="3"/>
 *               &lt;maxLength value="3"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonalAttributeType", propOrder = {
    "personalAttribute",
    "personalData"
})
public class PersonalAttributeType {

    @XmlElement(name = "PersonalAttribute", required = true)
    protected String personalAttribute;
    @XmlElement(name = "PersonalData", required = true)
    protected String personalData;

    /**
     * Gets the value of the personalAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalAttribute() {
        return personalAttribute;
    }

    /**
     * Sets the value of the personalAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalAttribute(String value) {
        this.personalAttribute = value;
    }

    /**
     * Gets the value of the personalData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalData() {
        return personalData;
    }

    /**
     * Sets the value of the personalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalData(String value) {
        this.personalData = value;
    }

}
