//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatementOfCapitalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatementOfCapitalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Capital" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TotalNumberOfIssuedShares">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                         &lt;totalDigits value="18"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ShareCurrency" type="{http://xmlgw.companieshouse.gov.uk}iso3currency"/>
 *                   &lt;element ref="{http://xmlgw.companieshouse.gov.uk}TotalAggregateNominalValue"/>
 *                   &lt;element name="Shares" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://xmlgw.companieshouse.gov.uk}ShareClass"/>
 *                             &lt;element name="PrescribedParticulars">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="4000"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element ref="{http://xmlgw.companieshouse.gov.uk}NumShares"/>
 *                             &lt;element name="AmountPaidDuePerShare">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}positiveDecimal">
 *                                   &lt;fractionDigits value="6"/>
 *                                   &lt;totalDigits value="15"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="AmountUnpaidPerShare">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}positiveDecimal">
 *                                   &lt;fractionDigits value="6"/>
 *                                   &lt;totalDigits value="15"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="AggregateNominalValue">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}positiveDecimal">
 *                                   &lt;totalDigits value="19"/>
 *                                   &lt;fractionDigits value="6"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatementOfCapitalType", propOrder = {
    "capital"
})
public class StatementOfCapitalType {

    @XmlElement(name = "Capital", required = true)
    protected List<StatementOfCapitalType.Capital> capital;

    /**
     * Gets the value of the capital property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capital property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapital().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatementOfCapitalType.Capital }
     * 
     * 
     */
    public List<StatementOfCapitalType.Capital> getCapital() {
        if (capital == null) {
            capital = new ArrayList<StatementOfCapitalType.Capital>();
        }
        return this.capital;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TotalNumberOfIssuedShares">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *               &lt;totalDigits value="18"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ShareCurrency" type="{http://xmlgw.companieshouse.gov.uk}iso3currency"/>
     *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}TotalAggregateNominalValue"/>
     *         &lt;element name="Shares" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://xmlgw.companieshouse.gov.uk}ShareClass"/>
     *                   &lt;element name="PrescribedParticulars">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="4000"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element ref="{http://xmlgw.companieshouse.gov.uk}NumShares"/>
     *                   &lt;element name="AmountPaidDuePerShare">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}positiveDecimal">
     *                         &lt;fractionDigits value="6"/>
     *                         &lt;totalDigits value="15"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="AmountUnpaidPerShare">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}positiveDecimal">
     *                         &lt;fractionDigits value="6"/>
     *                         &lt;totalDigits value="15"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="AggregateNominalValue">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}positiveDecimal">
     *                         &lt;totalDigits value="19"/>
     *                         &lt;fractionDigits value="6"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "totalNumberOfIssuedShares",
        "shareCurrency",
        "totalAggregateNominalValue",
        "shares"
    })
    public static class Capital {

        @XmlElement(name = "TotalNumberOfIssuedShares", required = true)
        protected BigInteger totalNumberOfIssuedShares;
        @XmlElement(name = "ShareCurrency", required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String shareCurrency;
        @XmlElement(name = "TotalAggregateNominalValue", required = true)
        protected BigDecimal totalAggregateNominalValue;
        @XmlElement(name = "Shares", required = true)
        protected List<StatementOfCapitalType.Capital.Shares> shares;

        /**
         * Gets the value of the totalNumberOfIssuedShares property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalNumberOfIssuedShares() {
            return totalNumberOfIssuedShares;
        }

        /**
         * Sets the value of the totalNumberOfIssuedShares property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalNumberOfIssuedShares(BigInteger value) {
            this.totalNumberOfIssuedShares = value;
        }

        /**
         * Gets the value of the shareCurrency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShareCurrency() {
            return shareCurrency;
        }

        /**
         * Sets the value of the shareCurrency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShareCurrency(String value) {
            this.shareCurrency = value;
        }

        /**
         * Gets the value of the totalAggregateNominalValue property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotalAggregateNominalValue() {
            return totalAggregateNominalValue;
        }

        /**
         * Sets the value of the totalAggregateNominalValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotalAggregateNominalValue(BigDecimal value) {
            this.totalAggregateNominalValue = value;
        }

        /**
         * Gets the value of the shares property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the shares property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getShares().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link StatementOfCapitalType.Capital.Shares }
         * 
         * 
         */
        public List<StatementOfCapitalType.Capital.Shares> getShares() {
            if (shares == null) {
                shares = new ArrayList<StatementOfCapitalType.Capital.Shares>();
            }
            return this.shares;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}ShareClass"/>
         *         &lt;element name="PrescribedParticulars">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="4000"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}NumShares"/>
         *         &lt;element name="AmountPaidDuePerShare">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}positiveDecimal">
         *               &lt;fractionDigits value="6"/>
         *               &lt;totalDigits value="15"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="AmountUnpaidPerShare">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}positiveDecimal">
         *               &lt;fractionDigits value="6"/>
         *               &lt;totalDigits value="15"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="AggregateNominalValue">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}positiveDecimal">
         *               &lt;totalDigits value="19"/>
         *               &lt;fractionDigits value="6"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "shareClass",
            "prescribedParticulars",
            "numShares",
            "amountPaidDuePerShare",
            "amountUnpaidPerShare",
            "aggregateNominalValue"
        })
        public static class Shares {

            @XmlElement(name = "ShareClass", required = true)
            protected String shareClass;
            @XmlElement(name = "PrescribedParticulars", required = true)
            protected String prescribedParticulars;
            @XmlElement(name = "NumShares", required = true)
            protected BigInteger numShares;
            @XmlElement(name = "AmountPaidDuePerShare", required = true)
            protected BigDecimal amountPaidDuePerShare;
            @XmlElement(name = "AmountUnpaidPerShare", required = true)
            protected BigDecimal amountUnpaidPerShare;
            @XmlElement(name = "AggregateNominalValue", required = true)
            protected BigDecimal aggregateNominalValue;

            /**
             * Gets the value of the shareClass property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShareClass() {
                return shareClass;
            }

            /**
             * Sets the value of the shareClass property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShareClass(String value) {
                this.shareClass = value;
            }

            /**
             * Gets the value of the prescribedParticulars property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrescribedParticulars() {
                return prescribedParticulars;
            }

            /**
             * Sets the value of the prescribedParticulars property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrescribedParticulars(String value) {
                this.prescribedParticulars = value;
            }

            /**
             * Gets the value of the numShares property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumShares() {
                return numShares;
            }

            /**
             * Sets the value of the numShares property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumShares(BigInteger value) {
                this.numShares = value;
            }

            /**
             * Gets the value of the amountPaidDuePerShare property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAmountPaidDuePerShare() {
                return amountPaidDuePerShare;
            }

            /**
             * Sets the value of the amountPaidDuePerShare property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAmountPaidDuePerShare(BigDecimal value) {
                this.amountPaidDuePerShare = value;
            }

            /**
             * Gets the value of the amountUnpaidPerShare property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAmountUnpaidPerShare() {
                return amountUnpaidPerShare;
            }

            /**
             * Sets the value of the amountUnpaidPerShare property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAmountUnpaidPerShare(BigDecimal value) {
                this.amountUnpaidPerShare = value;
            }

            /**
             * Gets the value of the aggregateNominalValue property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getAggregateNominalValue() {
                return aggregateNominalValue;
            }

            /**
             * Sets the value of the aggregateNominalValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setAggregateNominalValue(BigDecimal value) {
                this.aggregateNominalValue = value;
            }

        }

    }

}
