//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * List of any Subsidiary and Associated Undertakings
 * 
 * <p>Java class for SubsidiaryAndAssociatedUndertakingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubsidiaryAndAssociatedUndertakingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubCompanyName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}nonEmptyNameAddressString">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="160"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SubCompanyNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ShareDescription" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}otherDataString">
 *               &lt;maxLength value="50"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OtherDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://xmlgw.companieshouse.gov.uk}otherDataString">
 *               &lt;maxLength value="100"/>
 *               &lt;whiteSpace value="collapse"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubsidiaryAndAssociatedUndertakingsType", propOrder = {
    "subCompanyName",
    "subCompanyNumber",
    "shareDescription",
    "otherDetails"
})
public class SubsidiaryAndAssociatedUndertakingsType {

    @XmlElement(name = "SubCompanyName", required = true)
    protected String subCompanyName;
    @XmlElement(name = "SubCompanyNumber")
    protected String subCompanyNumber;
    @XmlElement(name = "ShareDescription")
    protected String shareDescription;
    @XmlElement(name = "OtherDetails")
    protected String otherDetails;

    /**
     * Gets the value of the subCompanyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCompanyName() {
        return subCompanyName;
    }

    /**
     * Sets the value of the subCompanyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCompanyName(String value) {
        this.subCompanyName = value;
    }

    /**
     * Gets the value of the subCompanyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCompanyNumber() {
        return subCompanyNumber;
    }

    /**
     * Sets the value of the subCompanyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCompanyNumber(String value) {
        this.subCompanyNumber = value;
    }

    /**
     * Gets the value of the shareDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShareDescription() {
        return shareDescription;
    }

    /**
     * Sets the value of the shareDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShareDescription(String value) {
        this.shareDescription = value;
    }

    /**
     * Gets the value of the otherDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherDetails() {
        return otherDetails;
    }

    /**
     * Sets the value of the otherDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherDetails(String value) {
        this.otherDetails = value;
    }

}
