//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:36:09 AM GMT 
//


package uk.gov.companieshouse.xmlgw;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TotalShareCapitalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TotalShareCapitalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TotalNumberShareIssued" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TotalAggregateNominalValue" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element ref="{http://xmlgw.companieshouse.gov.uk}Currency"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TotalShareCapitalType", propOrder = {
    "totalNumberShareIssued",
    "totalAggregateNominalValue",
    "currency"
})
public class TotalShareCapitalType {

    @XmlElement(name = "TotalNumberShareIssued", required = true)
    protected BigInteger totalNumberShareIssued;
    @XmlElement(name = "TotalAggregateNominalValue", required = true)
    protected BigInteger totalAggregateNominalValue;
    @XmlElement(name = "Currency", required = true)
    protected String currency;

    /**
     * Gets the value of the totalNumberShareIssued property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalNumberShareIssued() {
        return totalNumberShareIssued;
    }

    /**
     * Sets the value of the totalNumberShareIssued property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalNumberShareIssued(BigInteger value) {
        this.totalNumberShareIssued = value;
    }

    /**
     * Gets the value of the totalAggregateNominalValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalAggregateNominalValue() {
        return totalAggregateNominalValue;
    }

    /**
     * Sets the value of the totalAggregateNominalValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalAggregateNominalValue(BigInteger value) {
        this.totalAggregateNominalValue = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

}
