//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 09:38:00 AM GMT 
//


package uk.gov.companieshouse.xmlgw.header;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FormHeader">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CompanyNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="CompanyType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="EW"/>
 *                         &lt;enumeration value="SC"/>
 *                         &lt;enumeration value="NI"/>
 *                         &lt;enumeration value="R"/>
 *                         &lt;enumeration value="OC"/>
 *                         &lt;enumeration value="SO"/>
 *                         &lt;enumeration value="NC"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CompanyName">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://xmlgw.companieshouse.gov.uk/Header}nonEmptyNameAddressString">
 *                         &lt;minLength value="3"/>
 *                         &lt;maxLength value="160"/>
 *                         &lt;whiteSpace value="collapse"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CompanyAuthenticationCode" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="6"/>
 *                         &lt;maxLength value="8"/>
 *                         &lt;whiteSpace value="preserve"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="PackageReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Language" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="EN"/>
 *                         &lt;enumeration value="CY"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FormIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SubmissionNumber">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="6"/>
 *                         &lt;whiteSpace value="collapse"/>
 *                         &lt;minLength value="6"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;sequence minOccurs="0">
 *                     &lt;element name="ContactName" type="{http://xmlgw.companieshouse.gov.uk/Header}nameAddressString"/>
 *                     &lt;element name="ContactNumber">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;maxLength value="25"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                   &lt;element name="CustomerReference" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="25"/>
 *                         &lt;minLength value="0"/>
 *                         &lt;pattern value="[A-Za-z0-9]*"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DateSigned" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Form">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AdditionalInformation" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Document" maxOccurs="3" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Data">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary">
 *                         &lt;maxLength value="15000000"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="Filename" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="32"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ContentType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="application/vnd.hp-pcl"/>
 *                         &lt;enumeration value="application/xml"/>
 *                         &lt;enumeration value="application/pdf"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Category">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="MEMARTS"/>
 *                         &lt;enumeration value="SUPPNAMEAUTH"/>
 *                         &lt;enumeration value="ACCOUNTS"/>
 *                         &lt;enumeration value="SUPPEXISTNAME"/>
 *                         &lt;enumeration value="DEED"/>
 *                         &lt;enumeration value="DEEDSUPP"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "formHeader",
    "dateSigned",
    "form",
    "additionalInformation",
    "document"
})
@XmlRootElement(name = "FormSubmission")
public class FormSubmission {

    @XmlElement(name = "FormHeader", required = true)
    protected FormSubmission.FormHeader formHeader;
    @XmlElement(name = "DateSigned", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateSigned;
    @XmlElement(name = "Form", required = true)
    protected FormSubmission.Form form;
    @XmlElement(name = "AdditionalInformation")
    protected FormSubmission.AdditionalInformation additionalInformation;
    @XmlElement(name = "Document")
    protected List<FormSubmission.Document> document;

    /**
     * Gets the value of the formHeader property.
     * 
     * @return
     *     possible object is
     *     {@link FormSubmission.FormHeader }
     *     
     */
    public FormSubmission.FormHeader getFormHeader() {
        return formHeader;
    }

    /**
     * Sets the value of the formHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormSubmission.FormHeader }
     *     
     */
    public void setFormHeader(FormSubmission.FormHeader value) {
        this.formHeader = value;
    }

    /**
     * Gets the value of the dateSigned property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateSigned() {
        return dateSigned;
    }

    /**
     * Sets the value of the dateSigned property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateSigned(XMLGregorianCalendar value) {
        this.dateSigned = value;
    }

    /**
     * Gets the value of the form property.
     * 
     * @return
     *     possible object is
     *     {@link FormSubmission.Form }
     *     
     */
    public FormSubmission.Form getForm() {
        return form;
    }

    /**
     * Sets the value of the form property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormSubmission.Form }
     *     
     */
    public void setForm(FormSubmission.Form value) {
        this.form = value;
    }

    /**
     * Gets the value of the additionalInformation property.
     * 
     * @return
     *     possible object is
     *     {@link FormSubmission.AdditionalInformation }
     *     
     */
    public FormSubmission.AdditionalInformation getAdditionalInformation() {
        return additionalInformation;
    }

    /**
     * Sets the value of the additionalInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormSubmission.AdditionalInformation }
     *     
     */
    public void setAdditionalInformation(FormSubmission.AdditionalInformation value) {
        this.additionalInformation = value;
    }

    /**
     * Gets the value of the document property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the document property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocument().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormSubmission.Document }
     * 
     * 
     */
    public List<FormSubmission.Document> getDocument() {
        if (document == null) {
            document = new ArrayList<FormSubmission.Document>();
        }
        return this.document;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class AdditionalInformation {

        @XmlAnyElement(lax = true)
        protected Object any;

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAny(Object value) {
            this.any = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Data">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary">
     *               &lt;maxLength value="15000000"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="Filename" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="32"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ContentType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="application/vnd.hp-pcl"/>
     *               &lt;enumeration value="application/xml"/>
     *               &lt;enumeration value="application/pdf"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Category">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="MEMARTS"/>
     *               &lt;enumeration value="SUPPNAMEAUTH"/>
     *               &lt;enumeration value="ACCOUNTS"/>
     *               &lt;enumeration value="SUPPEXISTNAME"/>
     *               &lt;enumeration value="DEED"/>
     *               &lt;enumeration value="DEEDSUPP"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "data",
        "date",
        "filename",
        "contentType",
        "category"
    })
    public static class Document {

        @XmlElement(name = "Data", required = true)
        protected byte[] data;
        @XmlElement(name = "Date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;
        @XmlElement(name = "Filename")
        protected String filename;
        @XmlElement(name = "ContentType", required = true)
        protected String contentType;
        @XmlElement(name = "Category", required = true)
        protected String category;

        /**
         * Gets the value of the data property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getData() {
            return data;
        }

        /**
         * Sets the value of the data property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setData(byte[] value) {
            this.data = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

        /**
         * Gets the value of the filename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFilename() {
            return filename;
        }

        /**
         * Sets the value of the filename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFilename(String value) {
            this.filename = value;
        }

        /**
         * Gets the value of the contentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContentType() {
            return contentType;
        }

        /**
         * Sets the value of the contentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContentType(String value) {
            this.contentType = value;
        }

        /**
         * Gets the value of the category property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCategory() {
            return category;
        }

        /**
         * Sets the value of the category property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCategory(String value) {
            this.category = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class Form {

        @XmlAnyElement(lax = true)
        protected Object any;

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAny(Object value) {
            this.any = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CompanyNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="CompanyType" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="EW"/>
     *               &lt;enumeration value="SC"/>
     *               &lt;enumeration value="NI"/>
     *               &lt;enumeration value="R"/>
     *               &lt;enumeration value="OC"/>
     *               &lt;enumeration value="SO"/>
     *               &lt;enumeration value="NC"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CompanyName">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://xmlgw.companieshouse.gov.uk/Header}nonEmptyNameAddressString">
     *               &lt;minLength value="3"/>
     *               &lt;maxLength value="160"/>
     *               &lt;whiteSpace value="collapse"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CompanyAuthenticationCode" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="6"/>
     *               &lt;maxLength value="8"/>
     *               &lt;whiteSpace value="preserve"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="PackageReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Language" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="EN"/>
     *               &lt;enumeration value="CY"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FormIdentifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SubmissionNumber">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="6"/>
     *               &lt;whiteSpace value="collapse"/>
     *               &lt;minLength value="6"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;sequence minOccurs="0">
     *           &lt;element name="ContactName" type="{http://xmlgw.companieshouse.gov.uk/Header}nameAddressString"/>
     *           &lt;element name="ContactNumber">
     *             &lt;simpleType>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                 &lt;maxLength value="25"/>
     *               &lt;/restriction>
     *             &lt;/simpleType>
     *           &lt;/element>
     *         &lt;/sequence>
     *         &lt;element name="CustomerReference" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="25"/>
     *               &lt;minLength value="0"/>
     *               &lt;pattern value="[A-Za-z0-9]*"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "companyNumber",
        "companyType",
        "companyName",
        "companyAuthenticationCode",
        "packageReference",
        "language",
        "formIdentifier",
        "submissionNumber",
        "contactName",
        "contactNumber",
        "customerReference"
    })
    public static class FormHeader {

        @XmlElement(name = "CompanyNumber")
        protected BigInteger companyNumber;
        @XmlElement(name = "CompanyType")
        protected String companyType;
        @XmlElement(name = "CompanyName", required = true)
        protected String companyName;
        @XmlElement(name = "CompanyAuthenticationCode")
        protected String companyAuthenticationCode;
        @XmlElement(name = "PackageReference", required = true)
        protected String packageReference;
        @XmlElement(name = "Language")
        protected String language;
        @XmlElement(name = "FormIdentifier", required = true)
        protected String formIdentifier;
        @XmlElement(name = "SubmissionNumber", required = true)
        protected String submissionNumber;
        @XmlElement(name = "ContactName")
        protected String contactName;
        @XmlElement(name = "ContactNumber")
        protected String contactNumber;
        @XmlElement(name = "CustomerReference")
        protected String customerReference;

        /**
         * Gets the value of the companyNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCompanyNumber() {
            return companyNumber;
        }

        /**
         * Sets the value of the companyNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCompanyNumber(BigInteger value) {
            this.companyNumber = value;
        }

        /**
         * Gets the value of the companyType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyType() {
            return companyType;
        }

        /**
         * Sets the value of the companyType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyType(String value) {
            this.companyType = value;
        }

        /**
         * Gets the value of the companyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyName() {
            return companyName;
        }

        /**
         * Sets the value of the companyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyName(String value) {
            this.companyName = value;
        }

        /**
         * Gets the value of the companyAuthenticationCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyAuthenticationCode() {
            return companyAuthenticationCode;
        }

        /**
         * Sets the value of the companyAuthenticationCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyAuthenticationCode(String value) {
            this.companyAuthenticationCode = value;
        }

        /**
         * Gets the value of the packageReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPackageReference() {
            return packageReference;
        }

        /**
         * Sets the value of the packageReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPackageReference(String value) {
            this.packageReference = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLanguage(String value) {
            this.language = value;
        }

        /**
         * Gets the value of the formIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormIdentifier() {
            return formIdentifier;
        }

        /**
         * Sets the value of the formIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormIdentifier(String value) {
            this.formIdentifier = value;
        }

        /**
         * Gets the value of the submissionNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSubmissionNumber() {
            return submissionNumber;
        }

        /**
         * Sets the value of the submissionNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSubmissionNumber(String value) {
            this.submissionNumber = value;
        }

        /**
         * Gets the value of the contactName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactName() {
            return contactName;
        }

        /**
         * Sets the value of the contactName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactName(String value) {
            this.contactName = value;
        }

        /**
         * Gets the value of the contactNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactNumber() {
            return contactNumber;
        }

        /**
         * Sets the value of the contactNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactNumber(String value) {
            this.contactNumber = value;
        }

        /**
         * Gets the value of the customerReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerReference() {
            return customerReference;
        }

        /**
         * Sets the value of the customerReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerReference(String value) {
            this.customerReference = value;
        }

    }

}
